path: D:/Abbas/GitHub/PolygontoYOLO/dataset_crackyolo  # dataset root dir
train: D:/Abbas/GitHub/PolygontoYOLO/dataset_crackyolo/images/train  # train images (relative to 'path')
val: D:/Abbas/GitHub/PolygontoYOLO/dataset_crackyolo/images/val  # val images (relative to 'path')

# number of classes
nc: 1

# class names
names: ['Riss']